package main

const welcomeMessage = "Bienvenido a POC Serverless"
const initialState = "El estado actual de los datos es:"
const optionsTitle = "Elige una de las siguientes opciones:"
const option1 = "1. Ver el estado actual de tu monedero"
const option2 = "2. Insertar monedas"
const closeOption = "3. Salir"
const exceptionReader = "error"
const badFormatOption = "error"
const badFormatNumber = "error"
const closeMessage = "bye!"
const koC string = "ko"
const okC string = "ok"
const errorLambda string = "Error from Lambda services"
const awsError string = "Error getting an answer from AWS."
const errorRespAws string = "Error in response type parsing AWS."
