package main

const welcomeMessage = "Welcome to POC Serverless"
const initialState = "The current status of the data is:"
const optionsTitle = "Choose one of the following options:"
const option1 = "1. View the current status of the wallet"
const option2 = "2. Save coins"
const closeOption = "3. Exit"
const exceptionReader = "error"
const badFormatOption = "error"
const badFormatNumber = "error"
const closeMessage = "bye!"
const koC string = "ko"
const okC string = "ok"
const errorLambda string = "Error from Lambda services"
const awsError string = "Error getting an answer from AWS."
const errorRespAws string = "Error in response type parsing AWS."
const infoColor string = "\033[1;34m%s\033[0m"
const strongWhiteColor string = "\033[1;38m%s\033[0m"
